### ISSUE TITLE
Convention!!

### ISSUE THREAD

**Issue by ep1stas1s** [wooteco-datastructure/miniprojects-2019#4]
**각자 의견 추가해주세요**

**Comment by ep1stas1s** [comment]
### Git
- Git Flow
  - master
  - develop
  - feat
  - fix

- 상위 branch에 merge

  - Merge를 완료한 branch 삭제

    ```BASH
    $ git push origin --delete [branch_name]
    ```

- 위 상위 branch로 부터 branch를 생성하여, 다른 기능 구현

### Gradle
- lombok 적용
- build.gradle 작성 시, group, name, version 일체형으로 작성 및 (complie이 아닌)**implementation**으로 통일
- 앞 명령어(implementation, testImplementation 등)별로 정렬
- 주석으로 역할 명시...?

### Java
- 도메인 객체에 기본으로 equals(id만 비교), hashcode, toString 작성...
- 람다식 파라미터가 1개일 땐 괄호를 적지 않음
    ```java
    value -> value + 3;
    (prev, next) -> prev + next;
    ```
- 불필요한 공백 제거 (commit 시 reformat, Optimize import)
- RestController -> `/api` 로 시작

### Front
- Javscript는 Java와 마찬가지로 camel 표기법 적용
- css, html의 경우, dash(-)를 통해 합성어(?) 구분

**Comment by jinwookh** [comment]
좋습니다! :+1:

**Comment by imkimheejoo** [comment]
- 피드백 현황 이모지와 칸반보드 이용
- url 형식 https://blog.mwaysolutions.com/2014/06/05/10-best-practices-for-better-restful-api/ 을 준수
